version: '3.8'
services:
  fuse-appliance-template:
    container_name: fuse-appliance-template
    build: .
    restart: always
    env_file: .env
    ports:
        - ${API_PORT}:8000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - ${API_PORT}

